/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated/gallery'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedRoomRouteImport } from './routes/_authenticated/room'
import { Route as AuthenticatedUniverseRouteImport } from './routes/_authenticated/universe'
import { Route as AuthenticatedActivitiesIndexRouteImport } from './routes/_authenticated/activities.index'
import { Route as AuthenticatedActivitiesActivityIdRouteImport } from './routes/_authenticated/activities.$activityId'
import { Route as AuthenticatedSkyIndexRouteImport } from './routes/_authenticated/sky.index'
import { Route as AuthenticatedSkyObjectIdRouteImport } from './routes/_authenticated/sky.$objectId'
import { Route as AuthenticatedBoardBoardIndexRouteImport } from './routes/_authenticated/board.$board.index'
import { Route as AuthenticatedBoardBoardPostIdRouteImport } from './routes/_authenticated/board.$board.$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomRoute = AuthenticatedRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUniverseRoute = AuthenticatedUniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivitiesIndexRoute =
  AuthenticatedActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivitiesActivityIdRoute =
  AuthenticatedActivitiesActivityIdRouteImport.update({
    id: '/activities/$activityId',
    path: '/activities/$activityId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSkyIndexRoute = AuthenticatedSkyIndexRouteImport.update({
  id: '/sky/',
  path: '/sky/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkyObjectIdRoute =
  AuthenticatedSkyObjectIdRouteImport.update({
    id: '/sky/$objectId',
    path: '/sky/$objectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoardBoardIndexRoute =
  AuthenticatedBoardBoardIndexRouteImport.update({
    id: '/board/$board/',
    path: '/board/$board/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoardBoardPostIdRoute =
  AuthenticatedBoardBoardPostIdRouteImport.update({
    id: '/board/$board/$postId',
    path: '/board/$board/$postId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/me': typeof AuthenticatedMeRoute
  '/room': typeof AuthenticatedRoomRoute
  '/universe': typeof AuthenticatedUniverseRoute
  '/activities/$activityId': typeof AuthenticatedActivitiesActivityIdRoute
  '/sky/$objectId': typeof AuthenticatedSkyObjectIdRoute
  '/activities/': typeof AuthenticatedActivitiesIndexRoute
  '/sky/': typeof AuthenticatedSkyIndexRoute
  '/board/$board/$postId': typeof AuthenticatedBoardBoardPostIdRoute
  '/board/$board/': typeof AuthenticatedBoardBoardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/me': typeof AuthenticatedMeRoute
  '/room': typeof AuthenticatedRoomRoute
  '/universe': typeof AuthenticatedUniverseRoute
  '/activities/$activityId': typeof AuthenticatedActivitiesActivityIdRoute
  '/sky/$objectId': typeof AuthenticatedSkyObjectIdRoute
  '/activities': typeof AuthenticatedActivitiesIndexRoute
  '/sky': typeof AuthenticatedSkyIndexRoute
  '/board/$board/$postId': typeof AuthenticatedBoardBoardPostIdRoute
  '/board/$board': typeof AuthenticatedBoardBoardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/room': typeof AuthenticatedRoomRoute
  '/_authenticated/universe': typeof AuthenticatedUniverseRoute
  '/_authenticated/activities/$activityId': typeof AuthenticatedActivitiesActivityIdRoute
  '/_authenticated/sky/$objectId': typeof AuthenticatedSkyObjectIdRoute
  '/_authenticated/activities/': typeof AuthenticatedActivitiesIndexRoute
  '/_authenticated/sky/': typeof AuthenticatedSkyIndexRoute
  '/_authenticated/board/$board/$postId': typeof AuthenticatedBoardBoardPostIdRoute
  '/_authenticated/board/$board/': typeof AuthenticatedBoardBoardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/calendar'
    | '/dashboard'
    | '/equipment'
    | '/gallery'
    | '/me'
    | '/room'
    | '/universe'
    | '/activities/$activityId'
    | '/sky/$objectId'
    | '/activities/'
    | '/sky/'
    | '/board/$board/$postId'
    | '/board/$board/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/calendar'
    | '/dashboard'
    | '/equipment'
    | '/gallery'
    | '/me'
    | '/room'
    | '/universe'
    | '/activities/$activityId'
    | '/sky/$objectId'
    | '/activities'
    | '/sky'
    | '/board/$board/$postId'
    | '/board/$board'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipment'
    | '/_authenticated/gallery'
    | '/_authenticated/me'
    | '/_authenticated/room'
    | '/_authenticated/universe'
    | '/_authenticated/activities/$activityId'
    | '/_authenticated/sky/$objectId'
    | '/_authenticated/activities/'
    | '/_authenticated/sky/'
    | '/_authenticated/board/$board/$postId'
    | '/_authenticated/board/$board/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/room': {
      id: '/_authenticated/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof AuthenticatedRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/universe': {
      id: '/_authenticated/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof AuthenticatedUniverseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities/': {
      id: '/_authenticated/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof AuthenticatedActivitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities/$activityId': {
      id: '/_authenticated/activities/$activityId'
      path: '/activities/$activityId'
      fullPath: '/activities/$activityId'
      preLoaderRoute: typeof AuthenticatedActivitiesActivityIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sky/': {
      id: '/_authenticated/sky/'
      path: '/sky'
      fullPath: '/sky/'
      preLoaderRoute: typeof AuthenticatedSkyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sky/$objectId': {
      id: '/_authenticated/sky/$objectId'
      path: '/sky/$objectId'
      fullPath: '/sky/$objectId'
      preLoaderRoute: typeof AuthenticatedSkyObjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/board/$board/': {
      id: '/_authenticated/board/$board/'
      path: '/board/$board'
      fullPath: '/board/$board/'
      preLoaderRoute: typeof AuthenticatedBoardBoardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/board/$board/$postId': {
      id: '/_authenticated/board/$board/$postId'
      path: '/board/$board/$postId'
      fullPath: '/board/$board/$postId'
      preLoaderRoute: typeof AuthenticatedBoardBoardPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedRoomRoute: typeof AuthenticatedRoomRoute
  AuthenticatedUniverseRoute: typeof AuthenticatedUniverseRoute
  AuthenticatedActivitiesActivityIdRoute: typeof AuthenticatedActivitiesActivityIdRoute
  AuthenticatedSkyObjectIdRoute: typeof AuthenticatedSkyObjectIdRoute
  AuthenticatedActivitiesIndexRoute: typeof AuthenticatedActivitiesIndexRoute
  AuthenticatedSkyIndexRoute: typeof AuthenticatedSkyIndexRoute
  AuthenticatedBoardBoardPostIdRoute: typeof AuthenticatedBoardBoardPostIdRoute
  AuthenticatedBoardBoardIndexRoute: typeof AuthenticatedBoardBoardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedRoomRoute: AuthenticatedRoomRoute,
  AuthenticatedUniverseRoute: AuthenticatedUniverseRoute,
  AuthenticatedActivitiesActivityIdRoute:
    AuthenticatedActivitiesActivityIdRoute,
  AuthenticatedSkyObjectIdRoute: AuthenticatedSkyObjectIdRoute,
  AuthenticatedActivitiesIndexRoute: AuthenticatedActivitiesIndexRoute,
  AuthenticatedSkyIndexRoute: AuthenticatedSkyIndexRoute,
  AuthenticatedBoardBoardPostIdRoute: AuthenticatedBoardBoardPostIdRoute,
  AuthenticatedBoardBoardIndexRoute: AuthenticatedBoardBoardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
